dependencies:
- name: exposecontroller
  version: 2.3.114
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.114
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
